services:
  laravel:
    build:
      context: "./devops/Docker/dev/php"
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    image: tingut/app:beta
    pull_policy: never
    container_name: "laravel-tingut"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    # user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www/html
    networks:
      - tingut-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "php",
          "echo 'Health check starting...' && php-fpm-healthcheck --verbose && echo 'Health check passed' || (echo 'Health check failed' && exit 1)",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

    depends_on:
      mysql:
        condition: service_healthy
  vite:
    build:
      context: "./devops/Docker/dev/node"
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        USERNAME: ${USER:-kainga}
    container_name: vite-tingut
    volumes:
      - .:/var/www/html
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    depends_on:
      - laravel
  nginx:
    image: nginx:alpine
    container_name: nginx-tingut
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./devops/Docker/dev/nginx/templates:/etc/nginx/templates

    command: [nginx-debug, "-g", "daemon off;"]
    environment:
      - FPM_HOST=laravel
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    depends_on:
      laravel:
        condition: service_healthy

    networks:
      - tingut-network

  redis:
    image: redis:7-alpine
    container_name: redis-tingut
    ports:
      - "6379:6379"
    networks:
      - tingut-network

  mysql:
    image: "mysql/mysql-server:8.0"
    container_name: "mysql-tingut"
    # ports:
    #   - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - tingut-mysql:/var/lib/mysql
      - ./devops/Docker/dev/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - tingut-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin-tingut"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8080:80
    networks:
      - tingut-network
    depends_on:
      mysql:
        condition: service_healthy

networks:
  tingut-network:
    driver: bridge
  # Persistent storage for MySQL

volumes:
  tingut-mysql:
    driver: local
